cyrillic_to_latin.settings:
  type: config_object
  label: 'Cyrillic to Latin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    languages:
      type: sequence
      label: 'Languages'
      sequence:
        - type: string
          label: 'Language'
